### ISSUE TITLE
Pulse 3.5.2 crash on iOS 14

### ISSUE THREAD

**Issue by francuim-d** [kean/Pulse#169] opened 2023-03-02 08:32 UTC
Hello! First of all, thank you for your framework! It helps a lot and it is by far the most powerful logging tool.

But unfortunately, I encountered crash using it. 

**Pulse version: 3.5.2** 
**iOS version: 14.7.1 iPhone 7 Plus**  and **14.5 iPhone 12 Pro simulator** 

How to reproduce: Present Pulse view controller, watch http request info, then dismiss view controller with interactive gesture.

I'm presenting view controller like this:
```
override func motionEnded(_ motion: UIEvent.EventSubtype, with event: UIEvent?) {
    if motion == .motionShake {
        let pulseVC = PulseUI.MainViewController()
        topmostViewController?.present(pulseVC, animated: true)
    }
}
```

Here is stack trace:
```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x00000001955aec10 in objc_release ()
#1	0x000000018752b484 in -[_PFManagedObjectReferenceQueue _processReferenceQueue:] ()
#2	0x0000000187632abc in -[NSManagedObjectContext _processRecentChanges:] ()
#3	0x00000001876444fc in _performRunLoopAction ()
#4	0x000000018179a540 in __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ ()
#5	0x0000000181794b70 in __CFRunLoopDoObservers ()
#6	0x000000018179510c in __CFRunLoopRun ()
#7	0x00000001817947d0 in CFRunLoopRunSpecific ()
#8	0x0000000197ed6570 in GSEventRunModal ()
#9	0x00000001840c12d0 in -[UIApplication _run] ()
#10	0x00000001840c684c in UIApplicationMain ()
#11	0x00000001948eb87c in UIApplicationMain(_:_:_:_:) ()
#12	0x00000001000e0bf0 in static UIApplicationDelegate.main() ()
#13	0x00000001000e0b78 in static AppDelegate.$main() at .../AppDelegate.swift:7
#14	0x00000001000e0c74 in main ()
#15	0x0000000181473140 in start ()
```

**Comment by francuim-d** [comment] 2023-03-02 08:34
In Crashlytics here there is slightly different stack trace
```
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x23c10 objc_release + 16
1  CoreData                       0x39a88 -[_CDSnapshot dealloc] + 68
2  CoreData                       0x11e708 -[NSManagedObject _clearRawPropertiesWithHint:] + 324
3  CoreData                       0x40594 -[NSFaultHandler turnObject:intoFaultWithContext:] + 408
4  CoreData                       0x463dc -[NSManagedObject dealloc] + 80
5  CoreData                       0x27250 -[_PFManagedObjectReferenceQueue _processReferenceQueue:] + 896
6  CoreData                       0x1404d0 _performRunLoopAction + 296
7  CoreFoundation                 0x99540 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
8  CoreFoundation                 0x93b70 __CFRunLoopDoObservers + 588
9  CoreFoundation                 0x9410c __CFRunLoopRun + 1012
10 CoreFoundation                 0x937d0 CFRunLoopRunSpecific + 572
11 GraphicsServices               0x3570 GSEventRunModal + 160
12 UIKitCore                      0xb302d0 -[UIApplication _run] + 1052
13 UIKitCore                      0xb3584c UIApplicationMain + 164
14 libswiftUIKit.dylib            0x1387c UIApplicationMain(_:_:_:_:) + 100
```

**Comment by kean** [comment] 2023-03-27 02:21
Duplicate of https://github.com/kean/Pulse/issues/171

**Closed by kean** 2023-03-27 02:21 UTC
